env-local = ASPNETCORE_ENVIRONMENT=Local
env-dev = ASPNETCORE_ENVIRONMENT=Development
env-prev = ASPNETCORE_ENVIRONMENT=Preview

test-local:
	$(env-local) dotnet watch test
test-dev:
	$(env-dev) dotnet watch test
test-prev:
	$(env-prev) dotnet watch test
