env-local = ASPNETCORE_ENVIRONMENT=Local
env-dev = ASPNETCORE_ENVIRONMENT=Development
env-prod = ASPNETCORE_ENVIRONMENT=Production

test-local:
	$(env-local) dotnet watch test
test-dev:
	$(env-dev) dotnet watch test
test-prod:
	$(env-prod) dotnet watch test
