on:
  push:
    branches: [main]

jobs:
  run-prev-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - run: make install-tools
      - run: echo $APPSETTINGS_PREVIEW > appsettings.Preview.json
        env:
          APPSETTINGS_PREVIEW: ${{ secrets.APPSETTINGS_PREVIEW }}
      - run: make test-prev
