on:
  push:
    branches: [main]

jobs:
  run-prod-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - run: dotnet tool install -g dotnet-script
      - run: echo $APPSETTINGS_PRODUCTION > appsettings.Production.json
        env:
          APPSETTINGS_PRODUCTION: ${{ secrets.APPSETTINGS_PRODUCTION }}
      - run: make test-prod
